### ISSUE TITLE
Fix koi dependency issues, possibly with project-specific gem-set

### ISSUE THREAD

**Issue by Obversity** [katalyst/koi#288]
- Start Date: 2017-03-07
- Owner: PV
- RFC PR: 

# Summary

Get gem-set per project, to hopefully mitigate dependency issues when running lots of different koi projects locally

# Motivation

Dependency issues reduce productivity significantly when jumping on a new project. Having a gem-set per project might help mitigate that. 

# Detailed design

The KOI generator template could  be made to use the application name rather than the default (koi-gem or koiv2-gem).
Developers would need to ensure they have rbenv or rvm correctly set up to enable the use of gemsets. 
While most projects have the same gems installed, versions can be different due to the gems not being versioned in the gem file. Bundler will install what ever version is the latest on the day the project is created.

Currently, everything is dumped into the one shared gemset. So you end up with multiple versions of the same gems.

It is a cleaner separation to have a gemset per project, so the gemset would match the gemlock file versions. May help in debugging where functionality breaks between projects due to gem version issues.

# Drawbacks

No real drawback other than using a bit more disk space on your local machine. But we have plenty of that.

# Alternatives

Are gemsets the answer? 
Not sure of the exact problem that we are targeting or if it even solves a problem, it is just a cleaner separation and a tidier way to manage dependancies. Also could facilitate testing of different versions before updates but manually requiring a gemset to run locally with.

# Unresolved questions  

What are we trying to solve?

**Comment by Obversity** [comment]
@pvawser01 This is a bit loose, and I'm not even sure gemsets are the answer—does rbenv even support gemset or are they more of an rvm thing? I honestly don't know enough about the topic.

In either case, it'd be fantastic if for Koi 3 we could resolve the various dependency issues with gems and binstubs etc.

 Feel free to delete this issue, I just figured it'd be good as a reminder.

**Comment by pvawser01** [comment]
I've done some research and there might be a better way here. I'd like to discuss some options and see what everyone thinks.

**Comment by jsidoryn** [comment]
@pvawser01 is there any useful links that you could share. i'd be keen to be part of this discussion. i'll be in on friday and we can chat then but if there's anything you can add to this rfc it might help keep things going.

**Comment by jsidoryn** [comment]
@pvawser01 @Obversity would you guys mind jotting down the problem we are trying to solve. 

under motivation it says: 
_Dependency issues reduce productivity significantly when jumping on a new project._

this seems frustrating. what is the cause of it? is it the dependencies in gems we use that cause the problems or gems unexpectedly update to the latest version because it wasn't specified in the gemfile? something else?

**Comment by pvawser01** [comment]
A couple of links that may be of interest:
http://bundler.io/v1.2/bundle_install.html
http://ryan.mcgeary.org/2011/02/09/vendor-everything-still-applies/

**Comment by jsidoryn** [comment]
@pvawser01 thanks for sending them through. 

@Obversity do you have any thoughts on this? 

i had a bit of a look myself and couldn't find much on this approach and wondering why it isn't best practice? maybe just one of those things the people just put up with rather than sorting it out? 

i had a look at thoughtbot as are a similar company with lots of customers. didn't uncover much but these two things might be of interest. although not directly related may be one of the ways they help reduce problems. maybe not...

https://github.com/thoughtbot/appraisal
https://github.com/thoughtbot/suspenders
