### ISSUE TITLE
View module record on site

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#302]
- Start Date: 2017-03-21
- Owner: DB
- RFC PR: (leave this empty)

# Summary

Provide a button to view the module record on the website. 

# Motivation

Sometimes it can be awkward to find what you just created in Koi on the website. 

# Detailed design

Something like this:

![view-on-site](https://cloud.githubusercontent.com/assets/685024/24128630/0e18bbd6-0e2d-11e7-8233-9f699c91d910.jpg)

Obviously you can't view something on the site unless it's saved, so if the record is unsaved it either won't appear or would instead be replaced with this:

![screen shot 2017-03-21 at 11 52 17 am](https://cloud.githubusercontent.com/assets/685024/24128648/25125432-0e2d-11e7-9c24-89e746f9d56f.png)

Note: This is not a preview feature, like https://github.com/katalyst/koi/issues/233, this is just for providing a direct link to the resource on the front-end. 

Alternatively, these options could live down with the save/edit buttons:

![screen shot 2017-03-21 at 11 55 29 am](https://cloud.githubusercontent.com/assets/685024/24128669/4df44586-0e2d-11e7-901b-a75f633238e4.png)

# Drawbacks

Sometimes it won't be as easy as linking directly to the resource as it could be nested or appear in a subsite or any other sort of weird URL structure. 

# Unresolved questions

Should this link also be available from the index actions? Or the show page?

**Comment by Obversity** [comment]
I can definitely see the value in this, but I think it'd be  quite a bit of work to achieve per project, since we'd probably need to hardcode this per module, as our front-end routes aren't standard. A lot of things also don't have a 'show' page on the frontend (e.g. homepage tiles, or a resources module with no show page). 

It could be worth it, though. (It'd be a similar amount of work per-project to the feature we had in Stand, where as an admin on the front-end, you could visit the backend for that module with a hotkey.)

If we go ahead with it, I'd say it should be available from the index, edit and show views (and it should open in a new tab).

**Comment by jsidoryn** [comment]
Seems like it would be useful for clients. Could you have something in the Koi config that specifies the path to the show page. If it isn't included then the button doesn't display. 

Maybe the general case could be solved and even auto generated and the tricky ones just need to be done by hand.
