### ISSUE TITLE
Rename Sitemap Modules

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#303]
- Start Date: 2017-02-09
- Owner: DB
- RFC PR: (leave this empty)

# Summary

Rename "module" sitemap navitems to something more sensible. 
Review access of module navitems. 

# Motivation

"Module" navitems made sense when they were originally made. They were intended to be links to the modules. However they have since been used as a way to link to anything from module links, pages, short urls to external sites. 
"Module" doesn't really explain what it's used for any more. 

Secondly to this, "Module" navitems aren't available to regular admins, only superadmins. 
We should make it available to admins once we rename it. 

# Detailed design

We can either rename it on the front-end and make the name purely aesthetic or we could implement a new navitem type such as `url_navitem` or something and deprecate `module_navitem`. If we deprecate it we will need to do something about upgrades. 

Exposing it to regular admins is pretty simple. 

We could even make it configurable if a client is being mischievous:

```ruby
Koi::Sitemap::ModulesForSuperAdminsOnly = true
```

# Drawbacks

Could be confusing for users if all they want is to create pages. 

# Unresolved questions

The "Advanced" tab for navitems in general isn't available to regular admins either, which isn't too much of an issue since it is *advanced* stuff. The only thing they really miss out on is the ability to add or edit keys. Should we move keys to basic to remedy that or is that not a problem? 

What do we call the new navitem type? URL? Link? *NavItem*? 
Naming stuff is hard.

**Comment by Obversity** [comment]
Definitely worth doing! 'Module' is not very intuitive. I think I'd be in favour of 'link', because URL kind of implies it needs the http protocol + hostname, not just the path.

It might be as easy as renaming the class (in all locations). I don't think that'd even cause too many hassles upgrading, since I don't think I've ever seen us override Module Nav Item in the project. 

I don't think we need to give admins the ability to edit keys. Keys aren't really something they should be messing with, I don't think. And if know enough about koi to be messing with keys, we can probably just give them super admin privileges.

**Comment by dbaines** [comment]
> we can probably just give them super admin privileges.

That's a good point, I agree.

**Comment by jsidoryn** [comment]
The idea of the sitemap is that it reflects the navigation that is build on the front end. These are made up of 'Pages' and links that go into a module of some sort. The term 'module' is a little ambiguous as you say. It could be going directly to a contact form or a list of products or anything really. 

The main purpose of it being in the site tree is so that if they client wishes to move it around in the navigation, then they can do so. Providing a link to it to that module in the admin is really a convenience as it's the same way you get to edit a page. 

Another 'type' of thing that could go in the site tree is an external link. We have requests for this from time to time but I'm of the opinion that there should only be internal links in the site map. 

So with that background, where to from here? 

1. One option is to be more specific about what it links to. So we could have one icon for a link to a form and another for a list of things. Many other CMS's do this type of thing. 

2. Another option is to leave the structure how it is but have a different name rather than 'Module' and a different icon. 

3. The last one is to do away with that idea completely and just have pages as it's essentially a list of nav items. 

I don't have a strong opinion on this but thinking option 2.

**Comment by Obversity** [comment]
My main gripe is that I don't think 'module' is a very clear term at all, to clients *or* to developers. I remember when I started at Katalyst, I was definitely confused by it for a month or two, and Pete's asked me questions recently about exactly what module nav items do as well. 

I'm in favour of the easy solution, 2: leaving the structure basically how it is, changing the permissions so regular admins can create them, and renaming it to something more client friendly. (Maybe we could survey our clients and see what would make the most sense to them?)
