### ISSUE TITLE
Alternative hosting

### ISSUE THREAD

**Issue by pvawser01** [katalyst/koi#308]
Start Date: 2017-03-29
Owner: PV

# Summary

Improve hosting options for both cost affectiveness and maintainability of server infrastructure.
Cost considerations need to be for both client budgets as well as Katalyst's.

# Motivation

Currently we have quite a number of client applications lumped together on shared servers. While this keeps our hosting costs lower, it does cause issues with regards to server administration and potential performance issues.

Also, server capacity has not been considered to date as new apps come on line and the current shared servers are starting to be affected by memory bloat.

# Detailed design

It is important to remember that Engineyard is a premium service.
While engineyard provides benefits for scaling of high traffic applications and dev ops/server administration, it does come at a cost.

Many of our smaller clients don't have the budget for premium servers and may never reach the levels of demand that would require scaling of servers.

For this reason, a more cost affective option may be to have hosting tiers. Small apps could be hosted on a cheaper VPS on their own. 
While this would offer a cost affective alternative for smaller sites, it also prevents issues arising from noisy neighbours on the server, impacting on their apps performance.

It also provides Katalyst with additional revenue funnels for upgrade/scaling strategies as a client grows.

Server maintenance would be made easier as we could take one client at a time of line to perform upgrades to the server.

Alternatively, using the current model of shared servers on enginyard, could still be an option but we would need to determine limits to the number of apps being served from a single server. This could be as simple as:
 max-server-applications = monthly-server-cost / (minimum-monthly-client-invoice/3)
 max-server-applications = 2000/(600/3) Round up to nearest whole number
 max-server-applications = 10

When a server reaches it's max app limit, we spin up a new server and start adding to that.

# Drawbacks

**Cheaper VPS service**
This would mean that for smaller clients we would need to manage server infrastructure ourselves. So staff would be required to upskill in dev ops and server admin duties. That said, if there was a high amount of this work to do, we could look at new hires for a specialist server admin to maintain cloud server infrastructure.

Another drawback would be we would lose the tooling to make server admin a little easier that EY provides. However, this is not that much of an issue. 

In recent times, we have experienced a few issues with EY infrastructure and the turnaround time for assistance has not been great. There have also been times where we have determined the issue before EY tech support and had to tell them what is wrong with their system.

**Shared server**
The main drawback with this option would be the cost worn by Katalyst during a new server build. If a new shared server is spun up, until Katalyst would wear costs until at leat 4 apps are server from it.

# Alternatives

Stick with what we have.

# Unresolved questions

???

**Comment by Obversity** [comment]
Definitely worth looking into!

I think I'd only be in favour of this if we could streamline it to nearly the same degree as with Engineyard, though. 

Some thoughts:

- We'd want to keep Karo as a deployment tool for consistency, even if it just triggers Capistrano (or something similar) under the hood
- Ideally we should keep the folder structure on the server as similar as possible. Mainly I just want to be able to find config in the `/data/app_name/shared` directory, the current directory in `/data/app_name/current` and nginx config in (or symlinked to) `/data/nginx`, since these are the main things I have to fiddle with in Engineyard's setup and if they're different my brain will probably explode
- We'd want a well-documented (and perhaps largely scripted) process for bootstrapping a new app on a non-engineyard server
- The VPS service would probably need to have an Australian region if the client is Australian and most of the userbase is Australian (and perhaps for legal purposes in some cases)

It'd probably take a considerable amount of time working out a solid process, but I'm definitely happy to upskill in this area. 

It might be worth getting a proof of concept up there. I.e. take one of our existing apps (maybe something small like [detour](https://github.com/katalyst/det-v3) and get it deployed on a VPS, work out what the pain points are, work out whether we need to fork / patch Karo (should't need to if directory structure is the same on the server, should just be able to use cap deploy in the deploy command in .karo.yml) etc.

**Comment by Obversity** [comment]
It'd also be good to list what our VPS options are, and work out whether they need to be Australian for legal purposes. 

Popular / cost effective options:

- http://linode.com/pricing
- https://www.digitalocean.com/pricing
- https://www.vultr.com/pricing

I know that Vultr has Australian servers (in Sydney), while Linode and Digital Ocean do not. Keep in mind that some Australian ISPs have awful routing to Singapore as well. My ping to my singapore Linode vps is 350ms, which doesn't make for a good user experience on a website.

Binary Lane also has Australian servers, but they seem to be a bit more expensive. 
- https://www.binarylane.com.au/vps-hosting/linux-vps

Google Cloud doesn't seem to have Australian regions either. Taiwan would be the closest. 

Amazon's Lightsail (i.e. their DO equivalent) doesn't seem to have Australian regions yet either, and their pricing doesn't look as competitive. 

- https://amazonlightsail.com/pricing/

**Comment by jsidoryn** [comment]
Thanks for the chat and additional information at the dev catchup. Here's a quick summary of a few things from the meeting. 

Current strategy: 
Host: EngineYard
Tier 3: Shared - $600 / yr
Tier 2: Solo instance ~ +$3k (charged directly to the client with 15% loading)
Tier 3: Clustered environment - Custom setup for each client (charged directly to the client with 15% loading)

This is for the production server but we generally also have a staging server for clients, especially the non shared servers. 

The current implicit assumptions are:
- we are too small to focus on dev ops (although we assume that an amount of time will need to be spent ~ 20% currently)
- we want to specialise in building sites and this is where we make our money
- as long as we break even on costs, it's ok
- the most important thing is developer happiness and ease of deployment
- we need a low cost solutions for around $600/yr for clients

I list these assumptions so you know what they are but also so you can challenge them if you feel they should be. 

Some recent things: 
- Heath has strived for invoicing to better reflect what we do for clients in the hosting area - he may have some additional idea on what solutions we have to offer
- recently there have been some problems with EngineYard and their value is being questioned. 
- if we are going to change our strategy then it makes sense to do it for Koi 3 onwards.  

There aren't any real firm requirements except
- must have the option to be hosted in Australia

**Comment by jsidoryn** [comment]
Here are some additional notes from a follow up conversation with Peter. 

The summary is that EngineYard do offer a lot out of the box that we would otherwise have to do. It's not that we can't set up our own servers but it's not a core competency that is important to the business. 

It's a lot easier for us to make money by charging billable hours for Rails work done for clients then it is to up-skill and manage servers. There's also a lot of risk there as well.

**Comment by jsidoryn** [comment]
Consensus to stay with Comodo as service is good, price is reasonable and little benefit from going with Let's Encrypt.
