### ISSUE TITLE
generator for search functionality

### ISSUE THREAD

**Issue by pvawser01** [katalyst/koi#315]
- Start Date: 2017-03-04
- Owner: PV
- RFC PR: 

# Summary

*Add a generator to KOI to Implement basic search capabilities to a project.*

# Motivation

*Whenever we require search functionality in a project we typically implement it the same way. Thinking sphinx.*
*Having a generator to hook this functionality up would be a time saver in the development process.*

# Detailed design

*A generator could be added to KOI to add required gems to the gem file, run required migrations or third part generators. We could even have it build basic indices, if using thinking sphinx for each model in the application. Quicker to modify or delete unwanted fields than create each one at a time.*

# Drawbacks

*Would mean that we would be limited to the functionality of the chosen implementation (Gem)*

# Alternatives

*??*

# Unresolved questions

*Is there something better than Thinking Sphinx that we might want to consider*

**Comment by Obversity** [comment]
Can we rename this to "sitewide search", rather than just search? A lot of the search features we build are custom, and are not built with thinking sphinx—Fringe event search, oliveri sink search, fmc idea search, scc location search, etc.

> Is there something better than Thinking Sphinx that we might want to consider

This is probably worth looking into first, yeah. Would it be possible to use Postgres's built in fulltext search? I know the [pg_search](https://github.com/Casecommons/pg_search) gem supports searching / indexing multiple tables, and would be **a lot** less hassle to implement. A lot of our projects already have the gem, in fact. (I'd be happy to give this a try myself. I could pick a project that already has sphinx and implement pg_search next to it, then compare results for relevance etc.)

Otherwise, yes, I agree wholeheartedly, we should definitely build a generator for this, if we stick with Sphinx!

**Comment by jsidoryn** [comment]
if we can use pg_search that would be preferable. spinx is pretty heavy from what i understand and requires some setting up. it would be great to have a search we can turn on 'out of the box' so to speak. if pg_search doesn't deliver what the client is after then we can look to other solutions and charge for it. 

the least a client requires is a direct match, showing a snippet before and after of the text and a link to the page. 

other nice features are some sort of ranking eg page title should rank higher than if it's found in body etc

i came across this a while back but haven't read it. might be useful, might not

https://www.viget.com/articles/implementing-full-text-search-in-rails-with-postgres

**Comment by Obversity** [comment]
It looks like pg_search does support 'highlights', i.e. matching snippets. (Haven't tried it yet.)

**Comment by jsidoryn** [comment]
Awesome, I think we should push our hardest to see if we can use it as our default approach to search as it makes it vastly simpler. If client want something more then we can legitimately charge them as there's likely to be some fairly specific search functionality that they will be needing.
