### ISSUE TITLE
Generator to add api boiler plate code

### ISSUE THREAD

**Issue by pvawser01** [katalyst/koi#317]
- Start Date: 2017-04-03
- Owner: PV
- RFC PR: 

# Summary

*Add generator to allow for faster implementation of secure API functionality*

# Motivation

*Interaction with external systems is becoming more and more prevalent. It could be a handy to have a generator to implement the basic structure and authentication layer for an API to the applications we build.*

# Detailed design

*While the specific data access via an api is project specific there is a lot of time required to plumb the security layer up. A generator to add the authentication layer and basic code structure could significantly reduce time required to get an API up and running.*

# Drawbacks

*??*

# Alternatives

*??*

# Unresolved questions

*??*

**Comment by Obversity** [comment]
It'd be awesome to have an API generator, definitely! 

We'd have to agree on an API tool. The koi:admin_controller generator currently generates `ActiveModel::Serializer` classes for your model, so we could keep using that for serialisation maybe. As for the controller layer, I'd be happy using just inherited_resources controllers, maybe with some smart defaults, and helpers baked in for authorization, pagination, etc. 

In the API I recently built for YourSAy, I used the jsonapi_resources gem, but there were definitely pros and cons to it. 

The pros: 

- the response is jsonapi standard and as such, jsonapi clients should be able to interact with it very easily, providing a bunch of nice functionality out of the box. 
- reasonably good documentation, easy to implement, and provides nice tools for stuff like including associated records, filtering records, and pagination.

The cons:

- ...Easy to implement until you need to break from their CRUD pattern for some custom endpoint, in which case it gets a bit crazy, since you're not just dealing with regular ol' Rails controllers
- The jsonapi data structure feels way more complex than it needs to be—the data you're interested in several layers deep, so if you're not using a jsonapi client, it might suck. 

Would we want to generate some kind of documentation tool as well? Again, in the recent YourSAy API, I pulled apart [slate](https://github.com/lord/slate) (a middleman based documentation bootstrapper) and embedded it in the YourSAy app. It's not quite as easy to maintain as, say, something that parses comments in your API controllers and builds docs from that, but the end result is a bit nicer I think.

Here's [the YourSAy docs](http://ysa-v2.staging.katalyst.com.au/api/docs). (See the yoursay wiki for access details.)

**Comment by pvawser01** [comment]
@Obversity Yeah. I think were on the same page here. I like the idea of generating the documentation too. Often that part gets neglected. Think we could do something pretty cool with this to make api's a breeze.
