### ISSUE TITLE
Default i18n configuration is slow

### ISSUE THREAD

**Issue by sfnelson** [katalyst/koi#389]
See `config/initializers/i18n.rb`

Koi uses ActiveRecord to store internationalisations by default, which leads to a very large number of queries running when simple form renders a page. Consider adding a cache or reverting the default to 'simple'.

**Comment by Obversity** [comment]
For future reference, one solution we use for lots of our apps is to use the 'simple' backend as mentioned:

```
# config/initializers/koi.rb
I18n.backend = I18n::Backend::Simple.new
```

We're thinking this ought to be the default, unless the client specifically needs translations to be editable via Koi, which case extra work will need to be done. 

The sheer number of queries is only part of the problem causing slowness. The other part is in how Koi settings work and how many settings records are created. 

Koi settings are stored in the `translations` table. If you declare `has_crud settings: true` on a model, for each record in this table there'll be several `resource` setting rows in the database, as defined in your `koi.rb` (e.g. `title`, `meta_description`, and `meta_keywords`). 

This is the case even when you just wanted to use settings at the Model level. For example, let's say you have a Contact module, with a thanks page that does this:

```
<%= raw Contact.setting(:thanks, "<p>Thanks for contacting us!</p>", field_type: "rich_text") %>
```

And let's say it's a busy site and you have 10,000 contact submissions in your database. You now have an extra 30,000 records in the `translations` table, because every time a Contact record was created, it also created empty settings records for title, meta_description and meta_keywords.

So when sites start off, forms load quickly, as there are very few records in the translation table because there's not much data. But a few years down the track, you might find that form is now taking 30 seconds to load because the translations table has 1m mostly-empty records in it.
