### ISSUE TITLE
Issue with content tree items not being editable after save

### ISSUE THREAD

**Issue by jamiekatalyst** [katalyst/koi#608]
Steps to replicate:
for a page with existing content components in the tree, user makes a change and then saves the page. The component items are no longer editable. e.g. indent and edit the item

**Comment by AlanCornthwaiteKatalyst** [comment]
It appears to be due to a change in Koi that turned on Turbo Morph by default. 
When the page reloads we pre set the attributes of each content row to deny all edit options (indent, edit etc). 
Morph takes these attributes and set them on each row. 

A proposed solution is to ignore rule based attributes as morph is deciding what attributes to update.
PR outlining the change https://github.com/katalyst/content/pull/60

**Comment by sfnelson** [comment]
Fixed in latest content release
